---
- hosts: codedesktops,localhost
  vars:
    reqd_packages:
      - audacity
      - chromium-browser
      - ffmpeg
      - freeciv
      - git
      - gimp
      - inkscape
      - maven
      - openjdk-8-jdk
      - pasaffe
      - shutter
      - software-properties-common
      - unzip
    links:
      - eclipse-oxygen.desktop
      - yaoqiang.desktop
    scripts:
      - rm-bom.sh # Remove byte order mark from BPMN files that prevents deployment
      - trim.sh # Trim all trailing spaces from file
    yaoqiang_vsn:
      - 5.3.11

  tasks:
    - name: Check if keys exist
      stat:
        path: '/home/tstephen/.ssh/id_rsa'
      register: idrsa

    - name: Generate keys to connect to other machines
      shell: ssh-keygen -t rsa -f /home/tstephen/.ssh/id_rsa -P ''
      when: idrsa.stat.exists is undefined or idrsa.stat.exists == False

    - name: Install packages
      become: yes
      apt:
        state: present
        name: "{{ item }}"
      with_items: "{{ reqd_packages }}"

#    - name: Install the Python MySQL module
#      pip:
#        name: MySQL-python

    - name: Install Dropbox
      unarchive:
        remote_src: True
        src: "https://www.dropbox.com/download?plat=lnx.x86_64"
        dest: /home/tstephen/
        owner: tstephen
        group: tstephen
        mode: 0774
        creates: /home/tstephen/.dropbox-dist

    - name: Start Dropbox
      shell: /home/tstephen/.dropbox-dist/dropboxd &

    #- name: Install InSync for Google Drive syncing

    - name: Setup some utilities
      become: yes
      file:
        src: '/home/tstephen/GDrive/bin/{{ item }}'
        dest: '/usr/bin/{{ item }}'
        state: link
      with_items: "{{ scripts }}"

    - name: Install Eclipse
      unarchive:
        remote_src: True
        src: http://eclipsemirror.itemis.de/eclipse/technology/epp/downloads/release/oxygen/R/eclipse-java-oxygen-R-linux-gtk-x86_64.tar.gz
        dest: /home/tstephen/.local/share/
        owner: tstephen
        group: tstephen
        mode: 0774
        creates: /home/tstephen/.local/share/eclipse/eclipse

    - name: Setup desktop links
      become: yes
      file:
        src: '/home/tstephen/GDrive/config/_local_share_applications/{{ item }}'
        dest: '/usr/bin/{{ item }}'
        state: link
      with_items: "{{ links }}"

    - name: Install NodeJS from download as package manager is out of date
      become: yes
      unarchive:
        remote_src: True
        src: "https://nodejs.org/dist/v6.11.3/node-v6.11.3-linux-x64.tar.xz"
        dest: /var/lib
        owner: root
        group: root
        mode: 0774
        creates: /var/lib/node-v6.11.3-linux-x64

    - name: Setup NodeJS symlink
      become: yes
      file:
        src: /var/lib/node-v6.11.3-linux-x64/bin/node
        dest: /usr/bin/node
        state: link

    - name: Setup NPM symlink
      become: yes
      file:
        src: /var/lib/node-v6.11.3-linux-x64/bin/npm
        dest: /usr/bin/npm
        state: link

    - name: Install "gulp-cli" node.js package globally.
      become: yes
      npm:
        name: gulp-cli
        global: yes

    - name: Check if Yaoqiang exists
      stat:
        path: '/home/tstephen/.local/share/yaoqiang-bpmn-editor-{{yaoqiang_vsn}}.jar'
      register: yaoqiang

    - name: Install Yaoqiang
      get_url:
        url: https://sourceforge.net/projects/bpmn/files/latest/download?source=files
        dest: /home/tstephen/.local/share/
        owner: tstephen
        group: tstephen
        mode: 0666
      when: yaoqiang.stat.exists is undefined or yaoqiang.stat.exists == False

    - name: crontab to download db backups
      cron:
        name: "Download DB backups"
        minute: "0"
        hour: "9"
        job: "scp code.knowprocess.com:/var/backups/daily/*gz /var/backups/mysql"

