---
- hosts: codedesktops,localhost
  vars:
    reqd_packages:
      - docker
      - git
      - maven
      - openjdk-8-jdk
      - software-properties-common
      - unzip
    links:
      - eclipse-oxygen.desktop
      - yaoqiang.desktop
    scripts:
      - rm-bom.sh # Remove byte order mark from BPMN files that prevents deployment
      - trim.sh # Trim all trailing spaces from file
    snaps:
      - vscode
    yaoqiang_vsn:
      - 5.3.11

  tasks:
    - name: Check if keys exist
      stat:
        path: '/home/tstephen/.ssh/id_rsa'
      register: idrsa

    - name: Generate keys to connect to other machines
      shell: ssh-keygen -t rsa -f /home/tstephen/.ssh/id_rsa -P ''
      when: idrsa.stat.exists is undefined or idrsa.stat.exists == False

    - name: Install packages
      become: yes
      apt:
        state: present
        name: "{{ reqd_packages }}"

#    - name: Install the Python MySQL module
#      pip:
#        name: MySQL-python

    # Install snaps
    - name: Install snaps
      become: yes
      snap:
        name: '{{ snaps }}'
        classic: yes

    - name: Check if GDrive exists
      stat:
        path: '/home/tstephen/GDrive'
      register: gdrive

    - name: Setup some utilities
      become: yes
      file:
        src: '/home/tstephen/GDrive/bin/{{ item }}'
        dest: '/usr/bin/{{ item }}'
        state: link
      with_items: "{{ scripts }}"
      when: gdrive.stat.exists == True

    - name: Setup desktop links
      become: yes
      file:
        src: '/home/tstephen/GDrive/config/_local_share_applications/{{ item }}'
        dest: '/usr/bin/{{ item }}'
        state: link
      with_items: "{{ links }}"
      when: gdrive.stat.exists == True

    #- name: Install Eclipse
    # unarchive:
    #   remote_src: True
    #   src: 'https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2019-09/R/eclipse-java-2019-09-R-linux-gtk-x86_64.tar.gz'
    #   dest: /home/tstephen/.local/share/
    #   owner: tstephen
    #   group: tstephen
    #   mode: 0774
    #   creates: /home/tstephen/.local/share/eclipse/eclipse

    - name: Install NodeJS from download as package manager is out of date
      become: yes
      unarchive:
        remote_src: True
        src: 'https://nodejs.org/dist/latest-v10.x/node-v10.17.0-linux-x64.tar.gz'
        dest: /var/lib
        owner: root
        group: root
        mode: 0774
        creates: /var/lib/node-v10.17.0-linux-x64

    - name: Setup NodeJS symlink
      become: yes
      file:
        src: /var/lib/node-v10.17.0-linux-x64/bin/node
        dest: /usr/bin/node
        state: link

    - name: Setup NPM symlink
      become: yes
      file:
        src: /var/lib/node-v10.17.0-linux-x64/bin/npm
        dest: /usr/bin/npm
        state: link

    - name: Install "gulp-cli" node.js package globally.
      become: yes
      npm:
        name: gulp-cli
        global: yes

    - name: Check if Yaoqiang exists
      stat:
        path: '/home/tstephen/.local/share/yaoqiang-bpmn-editor-{{yaoqiang_vsn}}.jar'
      register: yaoqiang

   #- name: Install Yaoqiang
   #  get_url:
   #    url: https://sourceforge.net/projects/bpmn/files/latest/download?source=files
   #    dest: /home/tstephen/.local/share/
   #    owner: tstephen
   #    group: tstephen
   #    mode: 0666
   #  when: yaoqiang.stat.exists is undefined or yaoqiang.stat.exists == False

    - name: crontab to download db backups
      cron:
        name: "Download DB backups"
        minute: "0"
        hour: "9"
        job: "scp code.knowprocess.com:/var/backups/daily/*gz /var/backups/mysql"

