---
- hosts: codeservers
  become: yes
  vars:
    reqd_packages:
      - ansible
      - git
      - software-properties-common
      - unzip

  tasks:

    # This adds the repo but not the key - chocolate teapot!
    #- name: Add Ansible repository into sources list
    #  apt_repository:
    #    repo: deb http://ppa.launchpad.net/ansible/ansible/ubuntu xenial main
    #    state: present

    - name: Add Ansible repository into sources list
      become: yes
      command: apt-add-repository ppa:ansible/ansible

    - name: Ensure pre-reqs for ansible management
      become: yes
      apt: state=installed pkg={{ item }} update_cache=yes
      with_items: "{{ reqd_packages }}"

    # Create job like 34 4 * * * certbot-auto renew --quiet --no-self-upgrade
    #- name: crontab to autorenew certs
    #  cron:
    #    name: "Renew letsencrypt certificates regularly"
    #    minute: "34"
    #    hour: "4"
    #    job: "certbot-auto renew --quiet --no-self-upgrade"
    - name: Create backup dir and assign permissions
      file:
        path: '{{ backup_dir }}'
        owner: tstephen
        group: admin
        mode: 775

    - name: crontab to rotate db backups weekly
      cron:
        name: "Rotate DB backups weekly on Friday nights"
        minute: "30"
        hour: 23
        weekday: 5
        job: "cp /{{ backup_dir }}/daily/*sql.gz /home/{{ ansible_ssh_user }}/backups/weekly/"
        user: "{{ ansible_ssh_user }}"

    - name: crontab to rotate db backups monthly
      cron:
        name: "Rotate DB backups monthly"
        minute: "30"
        hour: 2
        day: 1
        job: "cp /{{ backup_dir }}/weekly/*sql.gz /home/{{ ansible_ssh_user }}/backups/monthly/"
        user: "{{ ansible_ssh_user }}"

    - name: Install the Python Gitlab module
      pip:
        name: pyapi-gitlab

    # Unfortunately cannot use this as it disables issues, both when set
    # explicitly and also if ommitted (default is supposed to be True)
    #- name: Create Gitlab Project in group Omny
    #  gitlab_project:
    #    server_url: http://code.knowprocess.com
    #    login_user: "{{ git_user }}"
    #    login_password: "{{ git_pass }}"
    #    name: "{{ item }}"
    #    group: omny
    #    issues_enabled: True
    #    wiki_enabled: False
    #    snippets_enabled: False
    #    state: present
    #  with_items: "{{ tenants }}"
