= ANSIBLE CONFIGURATION

Infrastructure management using Ansible

Sensitive stuff is encrypted with http://docs.ansible.com/ansible/playbooks_vault.html[Ansible Vault] put the decryption key in `~/.vault_pass.txt` (and make sure it is readable only by you!)

== Fetch roles from galaxy

  ansible-galaxy install geerlingguy.mysql

== Run playbook

  ansible-playbook --vault-password-file ~/.vault_pass.txt --user tstephen playbook.yml

== Overview of files and their purpose

=== Inventory

. Edit hosts file

----
ansible-vault --vault-password-file ~/.vault_pass.txt edit ansible/inventory/hosts
----

=== Playbooks

  INFO: On new droplets this playbook needs to be run with `--user root`. It includes creating a new remote user for future access. That username is defined in ansible/inventory/group_vars/servers.

* **ubuntu.yml:** Basic system setup

  INFO: The remaining playbooks should be run with the ssh user defined in the servers file above

* **dbservers.yml:** Install and configure MySQL

* **wordpress.yml:** Install / check configuration of a site

* **boot-apps.yml:** Install and configure a Spring Boot app
