---
- name: Install razor and pyzor
  apt: pkg={{ item }} update_cache=yes cache_valid_time=36000 state=present
  with_items:
    - razor
    - pyzor
  notify:
    - razor create
    - razor register
    - pyzor discover
