---
- name: Set Hostname
  hostname:
    name: "{{ mailserver_hostname }}"
  notify:
    - restart systemd-logind

- name: Re-gather Facts
  action: setup
  when: ansible_hostname != mailserver_fqdn

- name: Set FQDN per hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.1.1"
    line: "127.0.1.1 {{ mailserver_fqdn }} {{ mailserver_hostname }}"
    state: present
    backup: yes
  notify:
    - restart systemd-logind
